current_price = int(input())
current_price_print = str(current_price)
last_months_price = int(input())
change = int(current_price - last_months_price)
change_print = str(change)
mortgage = float((current_price * 0.051) / 12)
formatted_mortgage = str('{:.2f}'.format(mortgage))
print("This house is","$"+current_price_print,"." The change is","$"+change_print,"since last month.")
print("The estimated monthly mortgage is","$"+formatted_mortgage,".")
