red_amount = int(input())
green_amount = int(input())
blue_amount = int(input())
minValue = min(red_amount,green_amount,blue_amount)
print((red_amount-minValue),(green_amount-minValue),(blue_amount-minValue))